### PR TITLE
edit config for UAA and response operations

### PR DESCRIPTION
**Pull request by tej99**
Config update for: https://github.com/ONSdigital/response-operations-ui/pull/163

Response operations should directly sign in with UAA.

https://trello.com/c/oodNbXR2/100-response-operations-ui-should-sign-in-directly-using-uaa-not-via-backstage

### CODE REVIEW

**Comment by tej99** [comment]
@JamesGardiner working on it right now. Not sure weather to replace the ras-backstage client (no services should be using backstage for sign in anymore) or to to just add a new client to UAA.

**Comment by tej99** [comment]
[response-operations-ui should sign in directly using uaa (not via backstage)](https://trello.com/c/oodNbXR2/100-response-operations-ui-should-sign-in-directly-using-uaa-not-via-backstage)

**Comment by tej99** [comment]
@JamesGardiner PR up for concourse pipeline changes https://github.com/ONSdigital/ras-deploy/pull/9.

**Comment by JamesGardiner** [comment]
I'd add a new client to UAA - @gavinleeedwards can help with that I think

**Pull request merged**
