### PR TITLE
Added new rabbit environment variables

### PR DESCRIPTION
**Pull request by madeye-matt**

### CODE REVIEW

**Comment by madeye-matt** [comment]
Andrew merged these changes in already 
https://github.com/ONSdigital/ras-rm-docker-dev/pull/38

**Comment by andrewmil** [comment]
@JamesGardiner In Production these Environment variables are different as they point at different queues. In locally they'll point at different places though

**Comment by madeye-matt** [comment]
@JamesGardiner these aren't my changes - Mark gave me the values, I am just raising the PR
@tej99 I don't know if we need to remove RABBIT_AMQP entry, I don't know anything about the changes, just trying to get everyone up and running ASAP

**Comment by jcox-dev** [comment]
@tej99 @madeye-matt yes, that environment variable can now be deleted as only the newly named ones exist in the repo following [release 16](https://github.com/ONSdigital/ras-collection-instrument/pull/101).

**Comment by JamesGardiner** [comment]
@andrewmil if they are pointing at different queues, then the URLs should be the same. From what I have been told, it sounds like these point at different RabbitMQ cluster instances. Approving for now based on that knowledge.

**Comment by madeye-matt** [comment]
@jcox-dev removed the old definition now

**Pull request merged**
